services:
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    restart: always # Dato clave: Para que esto funcione realmente "al encender la PC", asegurate de que el servicio de Docker esté habilitado para arrancar con el sistema operativo (en Linux usás sudo systemctl enable docker).
    container_name: timescaledb-lgvektor
    environment:
      POSTGRES_USER: ${VITE_DB_USER:-user}
      POSTGRES_PASSWORD: ${VITE_DB_PASSWORD:-password}
      POSTGRES_DB: ${VITE_DB_NAME:-mydb}
    ports:
      - "5432:5432"
    volumes:
      - tsdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always # Dato clave: Para que esto funcione realmente "al encender la PC", asegurate de que el servicio de Docker esté habilitado para arrancar con el sistema operativo (en Linux usás sudo systemctl enable docker).
    container_name: frontend-lgvektor
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend
    networks:
      - mynetwork

  backend:
    build: ./backend
    restart: always # Dato clave: Para que esto funcione realmente "al encender la PC", asegurate de que el servicio de Docker esté habilitado para arrancar con el sistema operativo (en Linux usás sudo systemctl enable docker).
    container_name: backend-lgvektor
    ports:
      - "3000:3000"
    env_file: 
      - ./backend/.env
    depends_on:
      - timescaledb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mynetwork

volumes:
  tsdata:

networks:
  mynetwork: