services:
  timescaledb:
    image: timescale/timescaledb-ha:pg14-latest
    container_name: timescaledb-lgvektor
    environment:
      POSTGRES_USER: ${VITE_DB_USER:-user}
      POSTGRES_PASSWORD: ${VITE_DB_PASSWORD:-password}
      POSTGRES_DB: ${VITE_DB_NAME:-mydb}
    ports:
      - "5432:5432"
    volumes:
      - tsdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  # El Frontend (Vite) está en la raíz
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile # Asegurate que este Dockerfile no tenga 'pg'
    container_name: frontend-lgvektor
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/backend # Evita que el volumen de la raíz pise al backend
    networks:
      - mynetwork

  # El Backend está en la subcarpeta /backend
  backend:
    build: ./backend
    container_name: backend-lgvektor
    ports:
      - "3000:3000"
    env_file: 
      - ./backend/.env
    depends_on:
      - timescaledb
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mynetwork

volumes:
  tsdata:

networks:
  mynetwork:
